### ISSUE TITLE
Hint dialog boxes in welcome tour do not point to the right element

### ISSUE THREAD

**Issue by VishnuSanal** [Kukkee/Kukkee#133] opened 2021-05-06 18:43 UTC
**Describe the bug**
Refer to the screenshot provided. The bottom row is while using full-screen on my monitor & the top row is while using normally.

**To Reproduce**
Steps to reproduce the behaviour:
1. Refer to the welcome tour 

**Expected behaviour**
The dialogs point to their respective elements

**Screenshots**
![bitmap](https://user-images.githubusercontent.com/50027064/117349263-d084fa00-aec8-11eb-942b-fd22ad3704de.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: 1.24.82 Chromium: 90.0.4430.93 

PS: I mistakenly took the screenshots in forced dark mode. Hope that's okay!

**Comment by AnandBaburajan** [comment] 2021-05-06 18:46
Hey @VishnuSanal! Looks like you're using an old version of the client. Can you fetch the main branch or check the live site? :D

**Comment by VishnuSanal** [comment] 2021-05-06 19:04
Hello, @AnandBaburajan Thank you for the quick response!

I'm really sorry to have missed that. I looked into the new design. And, can't resist saying that it's awesome :)

Just a small thing I noticed in the welcome tour. Please refer to the screenshot

![image](https://user-images.githubusercontent.com/50027064/117351187-0cb95a00-aecb-11eb-99b3-f4aa08b837a6.png)

This is (5/6) and it appears to be so! This is not a bug. Just reporting. I first scrolled inside the time-picker view & it did not move! I had to move out of it & scroll to get the hint dialog visible.

Apart from this everything worked fine. :)

Regards

**Comment by AnandBaburajan** [comment] 2021-05-06 19:21
> looked into the new design. And, can't resist saying that it's awesome :)

Thanks :D

> This is (5/6) and it appears to be so! This is not a bug. Just reporting. I first scrolled inside the time-picker view & it did not move! I had to move out of it & scroll to get the hint dialog visible.

Ah, I thought this issue was fixed with the UI update because I'm not able to reproduce it on Chrome on Linux. Will check, thanks.

**Comment by AnandBaburajan** [comment] 2022-03-31 13:21
Closing this since there's no tour anymore.

**Closed by AnandBaburajan** 2022-03-31 13:21 UTC
Labels: bug
